[project]
name = "muckrock-llm-starter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipython>=9.5.0",
    "llm>=0.27.1",
    "llm-documentcloud>=0.1.1",
]
